### ISSUE TITLE
Missing euro

### ISSUE THREAD

**Issue by Antoninum** [ssimono/freecount#7]
Hello,

I started a count with 3 peoples and 2 expenses (100€ and 20€).
One euro is missing from the balance total.

See [https://freecount.s10a.dev/?box=b96e8bf9a82bf95144d908aa6b7a0d06](https://freecount.s10a.dev/?box=b96e8bf9a82bf95144d908aa6b7a0d06)

Thank you !

**Comment by eggman64** [comment]
@ssimono seems like [the rounding function](https://github.com/ssimono/freecount/blob/2fe3dab2836cc816513fdc4ff4a2fb04026db9dd/js/handlers/utils.js#L2) is behaving badly

https://jsbin.com/yubusocimi/edit

**Comment by ssimono** [comment]
Just merged PR #8.
[It seems](https://freecount.s10a.dev/?box=b96e8bf9a82bf95144d908aa6b7a0d06) to have fixed the issue. Thanks @Zepcome  for reporting and @eggman64 for jumping on it :partying_face:

**Comment by Antoninum** [comment]
That was fast!
Thank you! :)
